Algoritmo "calcular_area_circunferencia"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/02/2020
Var
// Seção de Declarações das variáveis 
R:real
A:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
leia(R)
A<-PI*R^2
escreva(A)

Fimalgoritmo